[package]
edition = "2021"
name = "async-counter"
version = "0.1.0"

[dependencies]
actix = "0.13"
actix-files = "0.6"
actix-web = "4.4"
actix-web-actors = "4.1"
env_logger = "0.11"
log = "0.4"
rand = "0.8"
yrs = "0.18"
serde = "1.0"
serde_json = "1.0"
